spring:
  data:
    mongodb:
      uri: "mongodb://localhost/SocialApp"
      port: 27017
      username: admin
      password: admin
      uuid-representation: standard
  application:
    name: feed-app

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

